# Informações principais do projeto
site_name: pynvest
site_url: https://pynvest.readthedocs.io/en/latest/
site_author: Thiago Panini
site_description : >-
  Um pacote Python capaz de utilizar processos de web scrapping para
  extrair informações e indicadores de ativos financeiros listados
  na bolsa de valores em sites especializados.

# Informações do repositório com o código fonte
repo_name: ThiagoPanini/pynvest
repo_url: https://github.com/ThiagoPanini/pynvest

# Copyright
copyright: |
  Copyright &copy; 2023-2024 <a href="https://github.com/ThiagoPanini"  target="_blank" rel="noopener">ThiagoPanini</a>

# Configuração do tema
theme:
  name: material

  # Diretório adicional para customização do tema
  custom_dir: docs/overrides

  # Customizando ícone no header da página
  # icon:
  #   logo: tmp

  # Configurando paleta de cores
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Toque para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Toque para modo claro

  # Configurando features da documentação
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy

# Navegação
nav:
  - Início:
    - pynvest: index.md
  
  - Quickstart:
    - Instalação: quickstart/instalacao.md
    - Arquitetura: quickstart/arquitetura.md
    - Design: quickstart/design.md

# Configurando extensões
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - markdown.extensions.tables
  - markdown.extensions.footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search:
      lang: pt-br
  - mkdocstrings
  - drawio_file
  - glightbox