# Informações principais do projeto
site_name: pynvest
site_url: https://pynvest.readthedocs.io/pt/latest/
site_author: Thiago Panini
site_description : >-
  Um pacote Python capaz de utilizar processos de web scrapping para
  extrair informações e indicadores de ativos financeiros listados
  na bolsa de valores em sites especializados.

# Informações do repositório com o código fonte
repo_name: ThiagoPanini/pynvest
repo_url: https://github.com/ThiagoPanini/pynvest

# Copyright
copyright: |
  Copyright &copy; 2023-2024 <a href="https://github.com/ThiagoPanini"  target="_blank" rel="noopener">Thiago Panini</a>

# Configurações extras da documentação
extra:
  # Redes sociais no footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThiagoPanini
      name: Thiago Panini no Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thiago-panini/
      name: Thiago Panini no LinkedIn
    - icon: fontawesome/brands/hashnode
      link: https://panini.hashnode.dev/
      name: Blog panini-tech-lab no Hashnode
  
  # Google Analytics
  analytics:
    provider: google
    property: G-TSTKJMFJS3
    feedback:
      title: Esta página foi útil?
      ratings:
        - icon: material/thumb-up-outline
          name: Sim, sensacional!
          data: 1
          note: >-
            Obrigado pelo seu feedback!
        - icon: material/thumb-down-outline
          name: Não, precisa de melhorias
          data: 0
          note: >- 
            Obrigado pelo seu feedback! Tentaremos melhorar!

# Configuração do tema
theme:
  name: material

  # Diretório adicional para customização do tema
  custom_dir: docs/overrides

  # Customizando ícone no header da página
  icon:
    logo: custom/custom-icon-32px
  
  # Customizando favicon (ícone da aba)
  favicon: assets/imgs/logo/logo-sem-nome.png

  # Configurando paleta de cores
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Toque para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Toque para modo claro

  # Configurando features da documentação
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy

# Navegação
nav:
  - Início:
    - pynvest: index.md
  
  - Quickstart:
    - Instalação: quickstart/instalacao.md
    - Arquitetura: quickstart/arquitetura.md
    - Design: quickstart/design.md

  - Scrappers:
    - scrappers/index.md
    - Fundamentus:
      - Documentação:
        - Classe Fundamentus: scrappers/fundamentus/mkdocstrings/fundamentus.md
      - Demos:
        - Coletando Tickers Listados na B3: scrappers/fundamentus/demos/extracao_tickers_de_ativos.md
        - Coletando Indicadores de Ativos: scrappers/fundamentus/demos/coleta_indicadores_de_ativo.md
      - Indicadores: 
        - Ações: scrappers/fundamentus/indicadores/acoes.md
        - FIIs: scrappers/fundamentus/indicadores/fiis.md
  
  - Tools:
    - O Módulo Pynvest Tools: tools/tools.md
    - Quickstart:
      - Chamando o Módulo: tools/quickstart.md
      - Variáveis do Módulo: tools/variaveis.md
    - Detalhes da Solução:
      - Arquitetura: tools/arquitetura.md
      - Recursos Provisionados: tools/recursos.md
      - Etapas do Processo: tools/processo.md
    - Exemplos de Análises: tools/queries.md

  - Contribuindo: contribuindo/contribuindo.md

# Configurando extensões
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - markdown.extensions.tables
  - markdown.extensions.footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search:
      lang: pt
  - mkdocstrings
  - drawio_file
  - glightbox
  - git-committers:
      repository: ThiagoPanini/pynvest
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css